name = "vitedge-vue"
type = "javascript"
account_id = "<YOUR ID>"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-03-22"

kv_namespaces = [
  { binding = "TEST_NAMESPACE1", id = "<ignored>", preview_id = "<ignored>" },
  { binding = "TEST_NAMESPACE2", id = "<ignored>", preview_id = "<ignored>" }
]

[site]
bucket = "dist/client"
entry-point = "."

[build]
command = ""
watch_dir = "dist/worker"

[build.upload]
format = "service-worker"
