name = "vitedge"
type = "webpack"
account_id = "<YOUR ID>"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
compatibility_date = "2022-03-22"

[env.vue.site]
bucket = "../vue/dist/client"
entry-point = "."

[env.react.site]
bucket = "../react/dist/client"
entry-point = "."
