name = "vitedge-react"
type = "javascript"
account_id = "<YOUR ID>"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-04-10"

#$ wrangler kv:namespace create "TEST_NAMESPACE" --preview
kv_namespaces = [{ binding = "TEST_NAMESPACE", preview_id = "<preview_id>" }]

[site]
bucket = "dist/client"
entry-point = "."

[build]
command = ""
watch_dir = "dist/worker"

[build.upload]
format = "service-worker"
